// GET route: 'read' queries to restaurants table
GET http://localhost:3000/restaurants

###

// POST route:
POST http://localhost:3000/restaurants

###

// POST route: 'create' entries to insert into reviews table
POST http://localhost:3000/reviews
content-type: application/json

{
  "restName": "Jaime's Overly-Friendly Pork Shack",
  "staffAtt": "inappropriate",
  "service": 2,
  "review": "The food is great, but the owner, Jaime, too interested in asking if we knew a strapping young man who works at costco tire center becasue he got a whiff of his hair once and fell in love. ",
  "recommend": "yes",
  "bathroom": "gritty"
}

###

POST http://localhost:3000/signup
content-type: application/json

{
  "firstName": "testName",
  "lastName": "testLastName",
  "email": "test@gmail.com",
  "pw": "testingPW123"
}

###

//LOGIN
POST http://localhost:3000/login
content-type: application/json

{
  "email": "test@gmail.com",
  "pw": "testingPW123"
}

###


